/**
 * Bootstrap/Phoenix CSS-variable names (read via getColor/getThemeColor)
 * → phoenix-tailwind design tokens (src/assets/css/theme.css).
 * Specific names first; bare colour names last.
 */
export const tokenMap = {
  'primary-bg-subtle': 'color-primary-subtle',
  'secondary-bg-subtle': 'color-secondary-subtle',
  'success-bg-subtle': 'color-success-subtle',
  'danger-bg-subtle': 'color-danger-subtle',
  'warning-bg-subtle': 'color-warning-subtle',
  'info-bg-subtle': 'color-info-subtle',
  'primary-lighter': 'color-primary-lighter',
  'primary-light': 'color-primary-light',
  'primary-dark': 'color-primary-dark',
  'primary-darker': 'color-primary-darker',
  'secondary-lighter': 'color-secondary-lighter',
  'secondary-light': 'color-secondary-light',
  'secondary-dark': 'color-secondary-dark',
  'secondary-darker': 'color-secondary-darker',
  'success-lighter': 'color-success-lighter',
  'success-light': 'color-success-light',
  'success-dark': 'color-success-dark',
  'success-darker': 'color-success-darker',
  'danger-lighter': 'color-danger-lighter',
  'danger-light': 'color-danger-light',
  'danger-dark': 'color-danger-dark',
  'danger-darker': 'color-danger-darker',
  'warning-lighter': 'color-warning-lighter',
  'warning-light': 'color-warning-light',
  'warning-dark': 'color-warning-dark',
  'warning-darker': 'color-warning-darker',
  'info-lighter': 'color-info-lighter',
  'info-light': 'color-info-light',
  'info-dark': 'color-info-dark',
  'info-darker': 'color-info-darker',
  'body-highlight-bg': 'background-color-subtle',
  'body-emphasis-bg': 'background-color-soft',
  'body-bg': 'background-color-default',
  'body-color': 'text-color-default',
  'body-highlight-color': 'text-color-highlight',
  'body-emphasis-color': 'text-color-emphasis',
  'secondary-color': 'text-color-muted',
  'tertiary-color': 'text-color-subtle',
  'quaternary-color': 'text-color-soft',
  'secondary-bg': 'background-color-muted',
  'tertiary-bg': 'background-color-highlight',
  'emphasis-bg': 'background-color-emphasis',
  'border-color-translucent': 'border-color-subtle',
  'border-color': 'border-color-default',
  'light-text-emphasis': 'text-color-emphasis',
  'dark-text-emphasis': 'text-color-emphasis',
  primary: 'color-primary',
  secondary: 'color-secondary',
  success: 'color-success',
  danger: 'color-danger',
  warning: 'color-warning',
  info: 'color-info',
  light: 'color-light',
  dark: 'color-dark',
  white: 'color-white',
  black: 'color-black',
  // second sweep (charts/editors outside the dashboard)
  'emphasis-color': 'text-color-emphasis',
  'secondary-text-emphasis': 'text-color-muted',
  'success-subtle': 'color-success-subtle',
  'warning-subtle': 'color-warning-subtle',
  'danger-subtle': 'color-danger-subtle',
  'secondary-subtle': 'color-secondary-subtle',
  'gray-100': 'color-gray-100',
  'gray-200': 'color-gray-200',
  'gray-300': 'color-gray-300',
  'gray-400': 'color-gray-400',
  'gray-500': 'color-gray-500',
  'gray-600': 'color-gray-600',
  'gray-700': 'color-gray-700',
  'gray-800': 'color-gray-800',
  'gray-900': 'color-gray-900',
  'gray-1000': 'color-gray-1000',
  'gray-1100': 'color-gray-1100',
};
